In [2]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

In [5]:
df=pd.DataFrame({
    'color':['red','blue','green','green','red','blue']
})

encoder=OneHotEncoder()

encoded=encoder.fit_transform(df[['color']]).toarray()

In [6]:
encoded

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [9]:
encoded_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [10]:
encoded_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [11]:
encoder.transform([['blue']]).toarray()

C:\Users\admin\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [14]:
pd.concat([df,encoded_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0