In [2]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [3]:
lbl_encoder=LabelEncoder()

In [4]:
df=pd.DataFrame({
    'color':['red','blue','green','green','red','blue']
})

In [5]:
df

   color
0    red
1   blue
2  green
3  green
4    red
5   blue

In [7]:
encoded=lbl_encoder.fit_transform(df[['color']])

C:\Users\admin\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [8]:
encoded

array([2, 0, 1, 1, 2, 0])

In [9]:
from sklearn.preprocessing import OrdinalEncoder

In [10]:
df1=pd.DataFrame({
    'size':['small','medium','large','medium','small','large']
})

df1

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [12]:
Oe=OrdinalEncoder(categories=[['small','medium','large']])

encoded_df=Oe.fit_transform(df1[['size']])

In [13]:
encoded

array([2, 0, 1, 1, 2, 0])